version: '3'

services:
  jenkins-docker:
    image: docker:dind
    privileged: true
    networks:
      jenkins:
        aliases:
          - docker
    ports:
      - "2376:2376"
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro

  jenkins:
    build: .
    ports:
      - "50000:50000"
      - "8080:8080"
    networks:
      jenkins:
    environment:
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
      DOCKER_HOST: tcp://docker:2376
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
      - .:/app # trying to access local git repo

networks:
  jenkins:

volumes:
  jenkins-data:
  jenkins-docker-certs:
